DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pages CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE pages (
  id SERIAL PRIMARY KEY NOT NULL,
  show_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  episode_id INTEGER NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
